services:
    app:
        container_name: staytus-app
        build:
            context: ./App
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            APP_KEY: ${APP_KEY}
            DB_CONNECTION: mysql
            DB_HOST: ${MYSQL_ROOT_HOST}
            DB_PORT: 3306
            DB_DATABASE: ${MYSQL_DATABASE}
            DB_USERNAME: ${MYSQL_USERNAME}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_PORT: 6379
        networks:
            - sail
        depends_on:
            - mysql
            - redis

    mysql:
        container_name: staytus-mysql
        build:
            context: .
            dockerfile: Dockerfile.database
        # ports:
        #     - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: '${MYSQL_ROOT_HOST:-%}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_USERNAME: '${MYSQL_USERNAME}'
        # volumes:
        # - 'sail-mysql:/var/lib/mysql'
        #     - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${MYSQL_ROOT_PASSWORD}'
            retries: 3
            timeout: 5s
        restart: unless-stopped

    redis:
        container_name: staytus-redis
        build:
            context: .
            dockerfile: Dockerfile.redis
        # ports:
        #     - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        restart: unless-stopped

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
